### PR TITLE
Implement gradient descent and step length rule

### PR DESCRIPTION
**Pull request by niinimaki**
This is my initial implementation of the mentioned methods. Please have a look at it.

### CODE REVIEW

**Comment by kohr-h** [comment]
I'll need to do some work on #5 first since I realized that with the current structure, we would have to write different functions for different types of step length rules, which I want to avoid. This is because those rules, at least now, have different signatures and cannot be handled uniformly. That's what #5 is going to change.

**Comment by aringh** [comment]
Also: there is already a gradient decent (or steepest decent) in the odl package, which has not been move yet (because I guess that the solvers implemented will be moved, no?) https://github.com/odlgroup/odl/blob/master/odl/operator/solvers.py

**Comment by kohr-h** [comment]
Exactly.

**Comment by aringh** [comment]
I tried to pull the branch, but I cannot find it... (I'm no expert in git).

Comments on the line search: there are two update rules in the paper from 88. Why did you choose the one you have implemeted? (I have not read the paper carefully, there might be an obvious reason. If so, please just let me know :) )

Also: when computing the step length I was advised earlier to do something like
` tmp = np.dot(a,b)`
`if tmp == 0`
` `` ` `return`
`step = 1/tmp `
to avoid potential division-with-zero errors.

**Comment by kohr-h** [comment]
The branch is on [Kati's fork](https://github.com/niinimaki/odl-solvers.git) of the repo. This was before I fixed her write permissions to the main repo.

Please go ahead discussing - I'll get back to the implementation details soon.

**Comment by niinimaki** [comment]
The one I implemented seem to be most used in literature. 
And yes we could add proper checks to avoid the potential division-with-zero errors.

**Comment by niinimaki** [comment]
This one is outdated - there's a new pull request not based on my fork.

**Pull request closed without merging**
